---
version: '3'

services:
  
  zookeeper-edu:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper-edu
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka-broker-edu:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    container_name: kafka-broker-edu
    depends_on:
      - zookeeper-edu
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-edu:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9093, EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-edu:9093, EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.server=WARN,kafka.network=WARN,kafka.coordinator=WARN,
                            kafka.common=WARN,kafka.log=WARN,kafka.utils=WARN,kafka.zookeeper=WARN,kafka.cluster=WARN,
                            kafka.zk=WARN,kafka.zk.KafkaZkClient=WARN,kafka.log.LogCleaner=WARN,state.change.logger=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    volumes:
      - my_edu_kafka_data:/var/lib/kafka/data

  schema-registry-edu:
    image: confluentinc/cp-schema-registry:5.3.0
    container_name: schema-registry-edu
    depends_on:
      - kafka-broker-edu
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka-broker-edu:9093"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-edu
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN

  kafdrop-edu:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop-edu
    depends_on:
      - kafka-broker-edu
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka-broker-edu:9093"

volumes:
  my_edu_kafka_data:
    driver: local
